### ISSUE TITLE
Use Favicon with Transparency

### ISSUE THREAD

**Issue by ryanwiemer** [dillonemorris/portfolio#2]
This is up to your personal taste but I would advise using a favicon with transparency so you don't have a white box. 

<img width="198" alt="screen shot 2019-01-15 at 10 30 29 am" src="https://user-images.githubusercontent.com/5171579/51216665-035eea80-18da-11e9-9327-76918fb6cc5e.png">

**Comment by dillonemorris** [comment]
Good catch! Thanks Ryan. I just pushed a fix for this. 

<img width="202" alt="Screen Shot 2019-05-02 at 9 15 14 AM" src="https://user-images.githubusercontent.com/27472341/57090079-d08b0780-6cba-11e9-835e-bde96f7c64f3.png">
