### ISSUE TITLE
Footer Jump on Initial Mount

### ISSUE THREAD

**Issue by ryanwiemer** [dillonemorris/portfolio#3]
This is super minor but on the initial mount, meaning when you first hit the website, as the page content is loading you see the header and footer next to each other. After the page mounts the content pushes the footer to the bottom. 

This can be solved by either mounting / unmounting the footer on each page transition or you can simply hide all content besides the header until it has mounted. Again, this only occurs on the initial mount not on a route change. 

Let me know if you want me to fix this for you. I just didn't want to overcomplicate your code if you don't care. 

![reload](https://user-images.githubusercontent.com/5171579/51216950-09090000-18db-11e9-8937-e63bb6dd4982.gif)

**Comment by dillonemorris** [comment]
@ryanwiemer I would love to get this fixed, feel free to submit a PR! Can't thank you enough for your help.

**Comment by ryanwiemer** [comment]
I submitted a PR with a fix. https://github.com/dillonmorris91/portfolio/pull/7
